name: TextResizer
author: nickolabs
category: Interface
tags: [text, resize, font-size]
#docs: http://devthought.com/projects/mootools/textboxlist/
#demo: http://devthought.com/wp-content/project/mootools/textboxlist/Demo/